#sudo: false  #### cannot be enabled due to tor installation
language: java
jdk:
  - oraclejdk8

env:

before_install:

install:
  - mvn install -q -DskipTests=true -B -q -Pall-inclusive-examples -Pdist -Pspark-${SPARK_VERSION} ${EXTRA}

script:
  - mvn test -B -Pspark-${SPARK_VERSION} ${EXTRA}
